[DEFAULT]
base_model = D:/stable-diffusion-webui/models/Stable-diffusion/AzureNihil/AzureNihil.ckpt
dataset_root_path = D:/DataSet/
save_model_as = ckpt
# linear, cosine, cosine_with_restarts, polynomial, constant, constant_with_warmup
lr_scheduler = cosine_with_restarts

resize_lora_path = D:/sd-scripts/networks/resize_lora.py
sd_scripts_path = D:/sd-scripts/

finetune_lr = 5e-6
finetune_batch_size = 1
finetune_train_step = 10000
finetune_resolution = 512

#                       0   1   2   3   4   5   6   7   8   9  10  11
chara_down_lr_weight = 0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
chara_mid_lr_weight = 0.0
#                     0   1   2   3   4   5   6   7   8   9  10  11
chara_up_lr_weight = 0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
#                       0   1   2   3   4   5   6   7   8   9  10  11
style_down_lr_weight = 0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
style_mid_lr_weight = 0.0
#                     0   1   2   3   4   5   6   7   8   9  10  11
style_up_lr_weight = 0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

lora_unet_lr = 1e-3
lora_text_encoder_lr = 5e-5
lora_prior_loss_weight = 1.0
lora_batch_size = 32
lora_train_step = 200
lora_network_dim = 8
lora_conv_dim = 1
lora_resolution = 512

lycoris_unet_lr = 1e-3
lycoris_text_encoder_lr = 5e-5
lycoris_prior_loss_weight = 1.0
lycoris_batch_size = 32
lycoris_train_step = 200
lycoris_network_dim = 8
lycoris_conv_dim = 1
lycoris_resolution = 512
