[DEFAULT]
model_path = D:/stable-diffusion-webui/models/Stable-diffusion/AzureNihil/AzureNihil.ckpt
sd_scripts_path = D:/sd-scripts/
dataset_root_path = D:/DataSet/
learning_rate_finetune = 5e-6
# linear, cosine, cosine_with_restarts, polynomial, constant, constant_with_warmup
lr_scheduler = cosine_with_restarts
train_step_finetune = 10000
resolution_finetune = 512
learning_rate_lora = 1e-3
batch_size_lora = 4
resolution_lora = 512
use_blip = False
