[DEFAULT]
model_path = D:/stable-diffusion-webui/models/Stable-diffusion/AzureNihil/AzureNihil.ckpt
lora_pruneder = D:/StableDiffusionTools/Model/LoRA_Pruneder.py
sd_scripts_path = D:/sd-scripts/
dataset_root_path = D:/DataSet/

# linear, cosine, cosine_with_restarts, polynomial, constant, constant_with_warmup
lr_scheduler = cosine_with_restarts

learning_rate_finetune = 5e-6
train_step_finetune = 10000
resolution_finetune = 512

unet_lr_lora = 1e-3
text_encoder_lr_lora = 1e-3
batch_size_lora_low = 32
batch_size_lora_high = 8
network_dim_lora = 64
resolution_lora_low = 512
resolution_lora_high = 1024

network_dim_lycoris = 32

save_model_as = ckpt
use_blip = False

